### ISSUE TITLE
[PE-D][Tester E] Inconsistent Email Validation: Disallowance of Valid Format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-1/tp#194]
There appears to be an inconsistency in email validation, as the application disallows email addresses that meet the specified requirements. For instance, the email address `johnd@x-x` is correctly formatted according to the stipulated requirements—it is at least two characters long, begins and ends with 'x,' and contains a single hyphen '-,' as outlined in the requirements. To ensure compliance with the specified criteria, the application should allow such valid email addresses.
![Screenshot 2023-11-03 at 4.38.12 PM.png](https://raw.githubusercontent.com/tiongjjyi/ped/main/files/8c6a8291-47f8-4659-ba2e-24b7196efdec.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tiongjjyi/ped#12

**Comment by vijay-shankaranand** [comment]
Not a valid scenario
