### ISSUE TITLE
[PE-D][Tester C] Deleting contact while viewing event goes back to home page.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T09-1/tp#208]
If you delete a linked contact while viewing an event, it goes bak to the homepage instead of staying on event.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nabonitasen/ped#7

**Comment by vijay-shankaranand** [comment]
Intentional design choice, as deleting the contact is done in the entire contact list, hence changes made should be reflected across the entire contact list
